baseURL: /

publishDir: "docs"
languageCode: en-us
title: "Coronavirus Guide for the F&B Industry"

canonifyURLs: true
enableRobotsTXT: true
sectionPagesMenu: main

params:
  ga_id: "UA-xxxxx-xx"
  description: "What it is, why it’s bad—and how you can help"
  keywords: ""
  cachebuster: ""
  name: "Vaughn Tan"
  email: me@vaughntan.org
  icon: fa-utensils


disableKinds:
  - section
  - section
  - taxonomy
  - taxonomyTerm
  - rss
  - section
  - page

